# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvmUt1n9x9tl2n6yLbA9DhjfbhVofkqm
"""

import os
import pandas as pd
import numpy as np
file_path = '/content/Housing.csv'
df = pd.read_csv(file_path)
print("First 5 rows of the dataset:")
print(df.head())
print("\nLast 5 rows of the dataset:")
print(df.tail())
print("\nData types of each column:")
print(df.dtypes)
duplicates_count = df.duplicated().sum()
print(f"\nNumber of duplicate rows in the dataset: {duplicates_count}")
print("\nColumn-wise null value count:")
print(df.isnull().sum())
rows, cols = df.shape
print(f"\nThe dataset contains {rows} rows and {cols} columns.")
if 'price' in df.columns:
    filtered_rows = df[df['price'] > 30]
    print("\nRows where 'price' is greater than 30:")
    print(filtered_rows)
else:
    print("\nThe 'price' column is not available in the dataset.")
if 'area' in df.columns:
    area_mean = df['area'].mean()
    df['area'] = df['area'].fillna(area_mean)
    print("\nMissing values in the 'area' column have been replaced with the column's mean.")
else:
    print("\nThe 'area' column is not available in the dataset.")
dataset_json = df.to_json()
print("\nDataset converted to JSON format (partial view):")
print(str(dataset_json)[:500])
output_file_path = '/content/updated_task_Housing.csv'
df.to_csv(output_file_path, index=False)
print(f"\nUpdated dataset has been saved to: {output_file_path}")